spring:
  application:
    name: vue-admin-service
  # Mysql数据库链接
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Jackson过滤掉空值
  jackson:
    default-property-inclusion: non_null


# 当前服务器占用的端口
server:
  port: 8081
  servlet:
    context-path: /iview-admin/

# Mybatis-plus 使用
mybatis-plus:
  type-aliases-package: com.zixuan007.admin.pojo
  mapper-locations: classpath:mapper/*.xml
  global-config:
    id-type: 2
    db-column-underline: true
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true


