spring:
  application:
    name: vue-admin-service
  ##数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 当前服务器占用的端口
server:
  port: 8081

#Mybatis-plus 使用
mybatis-plus:
  type-aliases-package: com.zixuan007.admin.pojo
  mapper-locations: classpath:mappers/*.xml
